Lesson 5
solidkime/ror-professional pull request #4
Opened 2017-03-18 23:14 UTC by solidkime

2017-03-19 12:11 UTC, palkan requested changes

2017-03-19 12:11 UTC, palkan commented on app/controllers/answers_controller.rb
> +      @question.reload
Зачем?

2017-03-19 12:11 UTC, palkan commented on app/controllers/answers_controller.rb
> +    if @answer.user.id == current_user.id
Не нужно делать лишнюю загрузку пользователя, просто `@answer.user_id == current_user.id`.

2017-03-19 12:11 UTC, palkan commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question was sucesfully created.'
Нужно проверить, что текст вопроса появился на странице

2017-03-19 12:11 UTC, palkan commented on spec/acceptance/create_answer_spec.rb
> +    expect(page).to have_content "Thank you for answer!"
Нужно проверить, что текст ответа есть на странице

2017-03-19 21:24 UTC, solidkime commented on app/controllers/answers_controller.rb
> +      @question.reload
Иначе во вьюху рендерится невалидный ответ (до рефреша).

2017-03-19 21:28 UTC, solidkime commented on spec/acceptance/create_question_spec.rb
> +    expect(page).to have_content 'Your question was sucesfully created.'
У меня он не должен появляться на странице, но ок, добавлю.

2017-03-20 17:54 UTC, vkurennov requested changes

2017-03-20 17:54 UTC, vkurennov commented on app/controllers/answers_controller.rb
> +    if @answer.user_id == current_user.id
Такая проверка еще не раз встретится, вынеси ее в метод `User#author_of?` и не забудь тесты написать на него.

2017-03-20 17:54 UTC, vkurennov commented on app/controllers/questions_controller.rb
> +    if current_user.id == @question.user_id
Замени на `User#author_of?`

2017-03-20 17:54 UTC, vkurennov commented on app/views/questions/index.html.slim
> +        td= "#{ question.title }"
Зачем тут интерполяция, у тебя и так тут строковые атрибуты

2017-03-20 17:54 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        td= "#{ answer.body }"
Опять лишняя интерполяция

2017-03-20 17:54 UTC, vkurennov commented on app/views/questions/show.html.slim
> +        - if user_signed_in?
Не каждому залогиненному юзеру надо показывать ссылку на удаление, только автору

2017-03-20 17:54 UTC, vkurennov commented on app/views/questions/show.html.slim
> +  p You should log in to leave comments
Это стоит вынести в лейаут, чтобы ссылки были на каждой странице

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/create_answer_spec.rb
> +feature 'Create answer', %q{
Нужен сценарий на невалидный ответ

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/create_question_spec.rb
> +feature 'Create question', %q{
Нужен сценарий на невалидный вопрос

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/destroy_answer_spec.rb
> +    expect(page).not_to have_content answer.body
Хорошо бы перед удалением проверить, что ответ есть на странице

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/destroy_answer_spec.rb
> +    click_on "Destroy answer"
Лучше вообще не показывать ссылку не-автору

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/destroy_question_spec.rb
> +    expect(page).not_to have_content question.body
Проверь, что до удаления вопрос был на странице

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/destroy_question_spec.rb
> +    click_on "Destroy"
Лучше не показывать ссылку не-автору

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/destroy_question_spec.rb
> +    expect(page).not_to have_content 'Destroy'
Лучше `to_not have_link`

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/index_questions_spec.rb
> +    expect(page).to have_content 'List of questions'
Здесь надо проверять как раз заголовки вопросов, потому что в этом главная ценность для юзера -он видит список вопросов. И вопросы должны быть разными (используй sequence в фабриках для этого)

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/index_questions_spec.rb
> +    expect(page).to have_content 'List of questions'
Нужно проверять текст ссылок на странице, а не статичные элементы

2017-03-20 17:54 UTC, vkurennov commented on spec/acceptance/show_question_spec.rb
> +    expect(page).to have_content answers[0].body
Ответы должны быть разными и лучше сделать штук 5 и проверить их в цикле

2017-03-20 17:54 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>      context 'with valid attributes' do
Тут нужно проверить, что ответ связывается с залогиненным пользователем

2017-03-20 17:54 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>  RSpec.describe AnswersController, type: :controller do
Где тесты на удаление?

2017-03-20 17:54 UTC, vkurennov commented on spec/controllers/answers_controller_spec.rb
>    describe "GET #index" do
У нас не должно быть index/show/new у ответа

2017-03-20 17:54 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>      context 'with valid attributes' do
Тут нужен тест на связь с залогиненным юзером

2017-03-20 17:54 UTC, vkurennov commented on spec/controllers/questions_controller_spec.rb
>    describe 'DELETE #destroy' do
У тебя в контроллере условие, вот и тесты должны быть на оба случая - когда условие выполняется и когда нет

2017-03-20 22:10 UTC, solidkime commented on app/views/questions/index.html.slim
> +        td= "#{ question.title }"
Забыл убрать :)

2017-03-23 09:55 UTC, palkan-th commented on app/controllers/answers_controller.rb
> +    @answer.question = @question
Лучше использовать ассоциацию для создания:

```ruby
@answer = @question.answers.new(answer_params)
```

Во-первых, так короче)
Во-вторых, в ассоциации могут быть определены дополнительные [коллбеки](http://api.rubyonrails.org/classes/ActiveRecord/Associations/ClassMethods.html#association-callbacks) (что, вообще говоря, плохая практика, но всё ж).

2017-03-23 09:55 UTC, palkan-th commented on spec/controllers/answers_controller_spec.rb
> +  # describe "GET #index" do
Не боимся удалять ненужный код. Не нужно мусорить в репозитории.

2017-03-23 09:55 UTC, palkan-th commented on spec/acceptance/index_questions_spec.rb
> +  given!(:questions) { create_list(:question, 5, user: user) }
Достаточно и 2х штук, не нужно создавать лишнее.

2017-03-23 10:13 UTC, solidkime commented on app/controllers/answers_controller.rb
> +    @answer.question = @question
Я так и делал, но ведь тогда мы создаем во вьюхе show невалтдный объек ответа, который отображается и придется добавлять код во вьюху.

2017-03-23 10:14 UTC, solidkime commented on spec/acceptance/index_questions_spec.rb
> +  given!(:questions) { create_list(:question, 5, user: user) }
Виталий в комментарии выше зареквестил 5

2017-03-28 17:40 UTC, merged